template = "https://github.com/giellalt/template-lang-und"
rev_id = 316
template_sha = "4ab8b281df40078b127cd15db6e63507b51b4424"

[replacements]
__GLOTTOLOG_ID__ = "west2392"
__REPO__ = "lang-mrj"
__UND2C__ = "mrj"
__UNDEFINED__ = "Western Mari"
__UND__ = "mrj"
